### ISSUE TITLE
AppKit not being called from main thread

### ISSUE THREAD

**Issue by adudney** [tomaka/glium#425]
I'm not sure how to handle this in a cross platform manner, but calling any AppKit method on a background thread is disallowed and undefined behavior (And Glium uses exclusively that)

This is a possible cause of the Glium examples beach-balling on Mac.

Note: I'm posting this to both Glium and Glutin's pages, as I'm not sure where it's best to solve this.

https://github.com/tomaka/glutin/issues/245

**Comment by tomaka** [comment]
I guess I can put the window in an `Arc` so that `poll_events` directly calls the underlying function instead of being polled from another thread.

**Comment by tomaka** [comment]
That won't fix the tests however.

**Comment by tomaka** [comment]
Could you try if it works now?

**Comment by adudney** [comment]
It no longer beachballs, but now it crashes with the extremely unhelpful error message of: "An unknown error occurred

To learn more, run the command again with --verbose"

When run with --verbose: "Process didn't exit successfully: `target/metallurgical_rust` (status=11)"

And this crash log: http://pastebin.com/kf2P41By

This seems to happen when I move the mouse, if I leave the mouse alone it just sits there without beach balling. Clicking or typing do not crash it, only moving the mouse.

**Comment by tomaka** [comment]
Could you try running one of glutin's examples to see if it comes from glutin?

**Comment by adudney** [comment]
Running the window example from Glutin has the same error, keyboard and clicks work fine, while mouse movement crashes with this crash report: http://pastebin.com/VjV4gWzd

**Comment by tomaka** [comment]
Thanks!

I opened https://github.com/tomaka/glutin/issues/248

**Comment by tomaka** [comment]
Hmm, glutin's example work for many people on OS/X, so could anyone else check if it works?
(@palango @camjackson @TyOverby ?)

**Comment by InfiniteDarkness** [comment]
The glutin examples have the same problem on my machine.

**Comment by TyOverby** [comment]
Yeah, the examples are breaking on my machine too.

https://gist.github.com/TyOverby/f456fd6f19c7e6257bda

**Comment by InfiniteDarkness** [comment]
I think this is an issue with glutin, not glium. I wouldn't be surprised if the issue with glium is fixed now, and that one of the more recent edits to the OS X code broke something, and that the bug in glium prevented the code that crashes it now from running.

**Comment by tomaka** [comment]
@InfiniteDarkness That's also what I think, but I'd like to be sure that it's fixed before closing this issue.

**Comment by camjackson** [comment]
In case you needed any more confirmations, glutin's window example gives me a beachball and a crash now. [Crash dump](https://gist.github.com/camjackson/86696ae7f5cc3d6ce760)

**Comment by tomaka** [comment]
Should be fixed now.

**Comment by camjackson** [comment]
Can confirm that the glutin examples seem to run fine for me. I'd already updated rustc though, so I'm not sure if glium works...

**Comment by InfiniteDarkness** [comment]
Glium doesn't crash anymore, and the beachball of death is gone now. We still don't have any events, though.

**Comment by tomaka** [comment]
Could you try again now that https://github.com/tomaka/glutin/pull/70 is merged?

**Comment by InfiniteDarkness** [comment]
I'm getting most events now, but glutin::Event::Closed (the one I actually care about) is still broken.

**Comment by tomaka** [comment]
At least it's getting better :)

It's probably a bug only in glutin now. Thanks!

**Comment by tomaka** [comment]
Follow-up: https://github.com/tomaka/glutin/issues/257
